import os
import datetime
import glob
import sys

def save_checkpoint(summary: str) -> str:
    """
    Saves an incremental summary of the conversation to a markdown file.
    
    Args:
        summary (str): The conversation summary generated by the agent.
        
    Returns:
        str: A status message containing the required context marker.
    """
    checkpoint_dir = ".checkpoints"
    os.makedirs(checkpoint_dir, exist_ok=True)
    
    # Generate timestamp and filename
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"checkpoint_{timestamp}.md"
    filepath = os.path.join(checkpoint_dir, filename)
    
    # Find the previous checkpoint to link them
    existing_checkpoints = sorted(glob.glob(os.path.join(checkpoint_dir, "*.md")))
    previous_file_link = ""
    if existing_checkpoints:
        previous_file = os.path.basename(existing_checkpoints[-1])
        previous_file_link = f"**Previous Checkpoint:** [{previous_file}](./{previous_file})\n\n"
    
    # Format the Markdown content
    markdown_content = (
        f"# Incremental Conversation Checkpoint\n\n"
        f"**Date:** {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        f"{previous_file_link}"
        f"## Summary (Since Last Checkpoint)\n\n"
        f"{summary}\n"
    )
    
    try:
        with open(filepath, "w", encoding="utf-8") as file:
            file.write(markdown_content)
        # This exact string MUST be returned so it enters the chat history
        return f"Success: Checkpoint saved to {filepath}\n[=== CHECKPOINT_MARKER ===]"
    except Exception as e:
        return f"Error: Failed to save checkpoint. Details: {str(e)}"

if __name__ == "__main__":
    if len(sys.argv) > 1:
        summary_input = " ".join(sys.argv[1:])
    else:
        summary_input = sys.stdin.read()
    print(save_checkpoint(summary_input))
